import os
import json
import time
import urllib.request
import ssl

ssl_context = ssl._create_unverified_context()

if os.path.exists(".env"):
    with open(".env", "r", encoding="utf-8") as f:
        for line in f:
            if line.strip().startswith("GITHUB_TOKEN="):
                os.environ["GITHUB_TOKEN"] = line.strip().split("=", 1)[1].strip()

token = os.environ.get("GITHUB_TOKEN")
if not token:
    print("Error: GITHUB_TOKEN not found!")
    exit(1)

with open("issues_summary.json", "r", encoding="utf-8") as f:
    issues = json.load(f)

repo = "KarelBerka/Alphafoldology"
url = f"https://api.github.com/repos/{repo}/issues"

created_issues = []

for idx, issue in enumerate(issues, 1):
    tags_str = ", ".join([f"`{t}`" for t in issue["tags"]])
    innovations_str = "\n".join([f"- {inn}" for inn in issue["innovations"]])
    
    title = issue["title"]
    body = f"""**Platform Source:** {issue['platform']}  
**Category:** {issue['category']}  
**Parent Node / Genealogy:** {issue['parent_node']}  
**Target Tags:** {tags_str}  

---

### 📌 Description & Context
{issue['description']}

### 🔗 Key Links & References
- **Primary Link:** [{issue['url']}]({issue['url']})
- **Reference / DOI:** [{issue['doi']}]({issue['doi']})

### ✨ Key Features & Innovations
{innovations_str}

### ⚖️ Strengths & Limitations
- **Strengths:** {issue['strengths']}
- **Limitations:** {issue['limitations']}

### 📋 Suggested Action Items for Alphafoldology
- [ ] Add tool entry to `tools_data_updated.json` / `tools_data.json` under `{issue['category']}`.
- [ ] Connect parent edge to `{issue['parent_node']}` in interactive genealogy map (`index.js`).
- [ ] Update metrics (stars, downloads, citation DOIs).
- [ ] Tag entry with: {tags_str}.

---
*Generated by Antigravity AI Agent for Alphafoldology hub.*
"""

    payload = {
        "title": title,
        "body": body,
        "labels": ["enhancement", issue["category"].lower().replace(" ", "-")]
    }
    
    req = urllib.request.Request(
        url,
        data=json.dumps(payload).encode("utf-8"),
        headers={
            "Authorization": f"token {token}",
            "Content-Type": "application/json",
            "User-Agent": "AlphafoldologyBot"
        },
        method="POST"
    )
    
    try:
        with urllib.request.urlopen(req, context=ssl_context) as resp:
            data = json.loads(resp.read().decode("utf-8"))
            print(f"[{idx}/{len(issues)}] Created GitHub Issue #{data['number']}: {title}")
            print(f"    URL: {data['html_url']}")
            created_issues.append({
                "number": data["number"],
                "url": data["html_url"],
                "title": title
            })
    except Exception as e:
        print(f"[{idx}/{len(issues)}] Failed to create issue '{title}': {e}")
        
    time.sleep(1)

with open("posted_issues_result.json", "w", encoding="utf-8") as f:
    json.dump(created_issues, f, indent=2, ensure_ascii=False)

print(f"\nAll done! Created {len(created_issues)} GitHub issues on {repo}.")
